# Generated by Django 4.0.5 on 2022-06-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mathhistory',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
