# Generated by Django 4.0.5 on 2022-06-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_profile_score_alter_mathhistory_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/profiles'),
        ),
    ]
