# Generated by Django 4.0.5 on 2022-06-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/images/profiles/avatar.svg', null=True, upload_to='static/images/profiles'),
        ),
    ]
