# Generated by Django 4.0.5 on 2022-06-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='score',
            new_name='points',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='avatar.svg', upload_to=''),
        ),
    ]
